### ISSUE TITLE
CSSReset attribute does not work!

### ISSUE THREAD

**Issue by ovelwe** [merely-ui/merely-ui#1]
### Description

When i use CSSReset in <MerelyProvider CSSReset={true}></MerelyProvider>
CSS does not reset

### Link to Reproduction

https://opis-cdn.tinkoffjournal.ru/mercury/in-out-suffering-cats.y0hebtbgrcqj..jpg

### Steps to reproduce

1. Add MerelyProvider
2. Insert CSSReset={true} attribute in MerelyProvider component
3. See error

### Merely UI Version

1.0.1

### Browser

Firefox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by blinovvvvvv** [comment]
fixed at v1.0.2 [release](https://github.com/merely-ui/merely-ui/releases/tag/%40merely-ui%2Freact%401.0.2)
